# GET ALL
GET http://localhost:3001/api/persons
Content-Type: application/json

### GET SINGLE
GET http://localhost:3001/api/persons/1
Content-Type: application/json

### POST/CREATE Person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Lennon",
    "number": "1234"
}

### DELETE Person Entry
DELETE http://localhost:3001/api/persons/3918405
Content-Type: application/json